[package]
name = "ifit"
version = "0.1.0"
authors = ["Tyler Southwick <tyler@northfuse.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
